export const FAVOURITES_ROUTE = '/favorites'
export const HISTORY_ROUTE = '/history'
export const SIGNIN_ROUTE = '/signin'
export const SIGNUP_ROUTE = '/signup'
export const COCKTAIL_ROUTE = '/cocktail'
export const NOTFOUND_ROUTE = '*'
export const BASE_COCKTAILS_URL = 'https://www.thecocktaildb.com/api/json/v1/1'
