import { Cocktail, NewCocktail } from '../store/interfaces'

export const transformResponseFromServer = (args: Cocktail[]): NewCocktail[] =>
  args.map((arg) => ({
    data: arg,
    id: arg.idDrink,
    name: arg.strDrink,
    category: arg.strCategory,
    type: arg.strAlcoholic,
    glass: arg.strGlass,
    image: arg.strDrinkThumb,
    instructions: arg.strInstructions,
    ingredients: [
      arg.strIngredient1,
      arg.strIngredient2,
      arg.strIngredient3,
      arg.strIngredient4,
      arg.strIngredient5,
      arg.strIngredient6,
      arg.strIngredient7,
      arg.strIngredient8,
      arg.strIngredient9,
      arg.strIngredient10,
      arg.strIngredient11,
      arg.strIngredient12,
      arg.strIngredient13,
      arg.strIngredient14,
      arg.strIngredient15,
    ],
    measures: [
      arg.strMeasure1,
      arg.strMeasure2,
      arg.strMeasure3,
      arg.strMeasure4,
      arg.strMeasure5,
      arg.strMeasure6,
      arg.strMeasure7,
      arg.strMeasure8,
      arg.strMeasure9,
      arg.strMeasure10,
      arg.strMeasure11,
      arg.strMeasure12,
      arg.strMeasure13,
      arg.strMeasure14,
      arg.strMeasure15,
    ],
  }))
